#!/usr/bin/env bash
# Configures Nginx to add a custom X-Served-By header on a brand new Ubuntu server

# Update and install Nginx if not installed
sudo apt-get update -y
sudo apt-get install nginx -y

# Backup default Nginx site
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak

# Add custom header X-Served-By with hostname
sudo sed -i "/server_name _;/a \    add_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo systemctl restart nginx