#!/usr/bin/env bash
# Fix Nginx to run and listen on port 80
apt-get update -y
apt-get install -y nginx
sed -i 's/listen [0-9]* default_server/listen 80 default_server/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:[0-9]* default_server/listen [::]:80 default_server/g' /etc/nginx/sites-enabled/default
nginx -t
service nginx restart
