#!/usr/bin/env bash
# Installs Nginx, configures it to listen on port 80, and serves Holberton text

apt-get update -y
apt-get install -y nginx

# Replace default page content
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Restart nginx without systemctl
service nginx restart
