#!/usr/bin/env bash
# Install nginx and configure default page

sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
