#!/usr/bin/env bash
# Configure nginx to use a custom 404 page

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i '/server_name _;/a \ \ error_page 404 /404.html;\n\ \ location = /404.html {\n\ \ \ \ internal;\n\ \ }' /etc/nginx/sites-enabled/default

sudo service nginx restart