#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page containing required text

apt-get update -y
apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Add 404 configuration
sed -i 's@^\(\s*server_name _;\)@\1\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}@' /etc/nginx/sites-enabled/default

service nginx restart
