#!/usr/bin/env bash
# Configure Nginx with a custom 404 page

apt-get update -y
apt-get install nginx -y

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a \ \ error_page 404 /404.html;\n\ \ location = /404.html {\n\ \ \ \ root /var/www/html;\n\ \ \ \ internal;\n\ \ }' /etc/nginx/sites-enabled/default

service nginx reload